2025-07-07 15:34:38,001 p=4425 u=root n=ansible WARNING| [WARNING]: No python interpreters found for host 192.168.56.131 (tried ['python3.13', 'python3.12', 'python3.11', 'python3.10',
'python3.9', 'python3.8', '/usr/bin/python3', 'python3'])

2025-07-07 15:34:38,001 p=4425 u=root n=ansible INFO| 192.168.56.131 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 192.168.56.131 closed.\r\n",
    "module_stdout": "/bin/sh: /usr/bin/python3: No such file or directory\r\n",
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
    "rc": 127
}
2025-07-07 15:34:38,189 p=4425 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python interpreter at /usr/bin/python3, but future
installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-07 15:34:38,189 p=4425 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
ok

2025-07-07 15:41:52,628 p=4536 u=root n=ansible WARNING| [WARNING]: No python interpreters found for host 192.168.56.131 (tried ['python3.13', 'python3.12', 'python3.11', 'python3.10',
'python3.9', 'python3.8', '/usr/bin/python3', 'python3'])

2025-07-07 15:41:52,628 p=4536 u=root n=ansible INFO| 192.168.56.131 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 192.168.56.131 closed.\r\n",
    "module_stdout": "/bin/sh: /usr/bin/python3: No such file or directory\r\n",
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
    "rc": 127
}
2025-07-07 15:41:52,860 p=4536 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python interpreter at /usr/bin/python3, but future
installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-07 15:41:52,860 p=4536 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
ok

2025-07-09 10:06:17,850 p=4411 u=root n=ansible INFO| PLAY [all] ************************************************************************************************
2025-07-09 10:06:17,858 p=4411 u=root n=ansible INFO| TASK [test_ansible_runner] ********************************************************************************
2025-07-09 10:06:18,425 p=4411 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python interpreter at
/usr/bin/python3, but future installation of another Python interpreter could change the meaning of that
path. See https://docs.ansible.com/ansible-core/2.18/reference_appendices/interpreter_discovery.html for
more information.

2025-07-09 10:06:18,425 p=4411 u=root n=ansible INFO| changed: [192.168.56.142]
2025-07-09 10:06:20,901 p=4411 u=root n=ansible INFO| fatal: [192.168.56.131]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.131 port 22: No route to host", "unreachable": true}
2025-07-09 10:06:20,902 p=4411 u=root n=ansible INFO| PLAY RECAP ************************************************************************************************
2025-07-09 10:06:20,902 p=4411 u=root n=ansible INFO| 192.168.56.131             : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2025-07-09 10:06:20,902 p=4411 u=root n=ansible INFO| 192.168.56.142             : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2025-07-11 14:43:22,939 p=6120 u=root n=ansible INFO| host01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.3 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 14:43:49,626 p=6132 u=root n=ansible INFO| host01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.3 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 14:44:27,243 p=6144 u=root n=ansible INFO| host01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.3 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 14:47:33,863 p=6168 u=root n=ansible INFO| host01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.3 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 14:49:11,779 p=6192 u=root n=ansible INFO| host01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.3 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 14:55:17,325 p=6236 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 14:55:17,325 p=6236 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 14:55:26,781 p=6236 u=root n=ansible INFO| 192.168.1.13 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.13 port 22: Connection timed out",
    "unreachable": true
}
2025-07-11 15:03:49,192 p=6476 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:03:49,192 p=6476 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:03:51,649 p=6476 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:03:51,661 p=6476 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:04:25,986 p=6581 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:04:25,986 p=6581 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:04:28,569 p=6581 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:04:28,576 p=6581 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:04:36,147 p=6684 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:04:36,147 p=6684 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:04:38,725 p=6684 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:04:38,729 p=6684 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:06:32,992 p=6839 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:06:32,992 p=6839 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:06:35,463 p=6839 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:06:35,471 p=6839 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:10:18,399 p=7963 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:10:18,399 p=7963 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:10:20,977 p=7963 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:10:20,981 p=7963 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:12:04,052 p=8095 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:12:04,052 p=8095 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:12:06,483 p=8095 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:12:06,484 p=8095 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:29,828 p=8715 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:13:29,828 p=8715 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:13:32,413 p=8715 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:32,417 p=8715 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:44,399 p=8829 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:13:44,400 p=8829 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:13:50,494 p=9273 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:13:50,494 p=9273 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:13:50,665 p=9275 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:13:50,665 p=9275 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:13:50,706 p=9279 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:13:50,706 p=9279 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:13:51,443 p=9273 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:51,443 p=9273 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:51,445 p=9275 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:51,445 p=9275 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:51,447 p=9279 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:13:51,447 p=9279 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:14:47,406 p=9693 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-11 15:14:47,406 p=9693 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
1.sh
anaconda-ks.cfg
ansible.log
ansible_run
dump.rdb
examples
inventory
project
project1
redis-7.2.0
redis-7.2.0.tar.gz
requirements.txt
share
sudo-1.9.15-1.el7.x86_64.rpm
sudo-1.9.5-2.el7.x86_64.rpm
sudo.sh

2025-07-11 15:14:49,994 p=9693 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:14:50,002 p=9693 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:16:57,334 p=9966 u=root n=ansible INFO| 192.168.56.142 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.142 port 33: Connection refused",
    "unreachable": true
}
2025-07-11 15:17:00,347 p=9966 u=root n=ansible INFO| 192.168.56.140 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.140 port 22: No route to host",
    "unreachable": true
}
2025-07-11 15:17:00,351 p=9966 u=root n=ansible INFO| 192.168.56.144 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.56.144 port 22: No route to host",
    "unreachable": true
}
